### ISSUE TITLE
vaadinPrepareFrontend fails with Invalid object

### ISSUE THREAD

**Issue by mcooper7290** [vaadin/vaadin-gradle-plugin#104]
**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, iOS] Windows 10 + Cygwin
 - JDK version:  8
 - Gradle version:  6.8.3
 - Vaadin Plugin version:  0.14.3.7

**Describe the bug**
When building target 'vaadinPrepareFrontend' the build fails with Invalid object:

> Task :WebApp:vaadinPrepareFrontend FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':WebApp:vaadinPrepareFrontend'.
> Invalid object:

* Try:
....

This occurs when running 'gradle --stop; gradle clean assemble vaadinPrepareFrontend'

The same command with --stacktrace is attached.

[build-stacktrace.txt](https://github.com/vaadin/vaadin-gradle-plugin/files/6111299/build-stacktrace.txt)

**To Reproduce**
1. Setup project  '...'
2. Run Gradle task '....''
4. See error '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mcooper7290** [comment]
I fixed my issue by deleting all the project *.js and node_modules/* files.  It would be nice if the exception was caught and output the name of the file it can't parse.

**Comment by mvysny** [comment]
From the stacktrace
```
Caused by: elemental.json.JsonException: Invalid object: 
	at elemental.json.impl.JsonTokenizer.parseObject(JsonTokenizer.java:275)
	at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:173)
	at elemental.json.impl.JsonTokenizer.parseObject(JsonTokenizer.java:231)
	at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:173)
	at elemental.json.impl.JsonTokenizer.parseObject(JsonTokenizer.java:231)
	at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:173)
	at elemental.json.impl.JreJsonFactory.parse(JreJsonFactory.java:64)
	at elemental.json.Json.parse(Json.java:53)
	at com.vaadin.flow.server.frontend.NodeUpdater.getJsonFileContent(NodeUpdater.java:209)
	at com.vaadin.flow.server.frontend.NodeUpdater.getPackageJson(NodeUpdater.java:192)
	at com.vaadin.flow.server.frontend.TaskCreatePackageJson.execute(TaskCreatePackageJson.java:47)
```

it can be seen that Vaadin is trying to parse the `package.json` and failing. The file must have had some funny non-JSON contents for some reason. However, certainly Vaadin should have reported this error in a much more cleaner way. Could you please open a bug report at https://github.com/vaadin/flow/issues in this regard?

**Comment by mvysny** [comment]
Reported upstream: https://github.com/vaadin/flow/issues/10323
