### ISSUE TITLE
Vaadin 14.6.0: IllegalArgumentException: wrong number of arguments

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-gradle-plugin#113]
**Desktop (please complete the following information):**
 - OS: Ubuntu
 - JDK version: 11
 - Gradle version: 7.0
 - Vaadin Plugin version: 0.14.5.1

**Describe the bug**
Building Vaadin 14.6.0 app for production fails with

```
Caused by: java.lang.IllegalArgumentException: wrong number of arguments
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.vaadin.flow.server.webcomponent.WebComponentModulesWriter$DirectoryWriter.generateWebComponentsToDirectory(WebComponentModulesWriter.java:237)
        at com.vaadin.flow.server.frontend.FrontendWebComponentGenerator.generateWebComponents(FrontendWebComponentGenerator.java:85)
        at com.vaadin.flow.server.frontend.NodeTasks.<init>(NodeTasks.java:440)
        at com.vaadin.flow.server.frontend.NodeTasks.<init>(NodeTasks.java:47)
```

**To Reproduce**
1. git clone https://github.com/mvysny/karibu10-helloworld-application
2. v-bump Vaadin to 14.6.0 and Karibu-Testing to 1.3.0

**Expected behavior**
The plugin should work

**Comment by mvysny** [comment]
Fixed by 3d0facc16680b148c9580d3a0d724210d420e5a9 , the fix will be present in plugin version 0.14.6.0
