### ISSUE TITLE
Conflict with Vaadin 8 plugin

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-gradle-plugin#26]
When both `com.devsoap.plugin.vaadin` and `com.vaadin` plugins are used in the same project (usually the MPR), they both publish `vaadin{}` Gradle configuration extension which conflicts and will make Gradle fail with an exception. The simplest solution is to rename the extension of `com.vaadin` to something else. Options:

1. Make `com.vaadin` to rename the extension to something else only when `com.devsoap.plugin.vaadin` is discovered? OR
2. Rename the `com.vaadin` extension permanently to something else.

Possible new names:
1. `vaadin10`
2. `vaadin14`
3. `vaadinFlow`
4. Possibly others?

@mstahv what is your opinion please?

**Comment by mvysny** [comment]
The exception, for future reference:
```
Caused by: java.lang.IllegalArgumentException: Cannot add extension with name 'vaadin', as there is an extension already registered with that name.
        at org.gradle.internal.extensibility.ExtensionsStorage.add(ExtensionsStorage.java:40)
        at org.gradle.internal.extensibility.DefaultConvention.add(DefaultConvention.java:119)
        at org.gradle.internal.extensibility.DefaultConvention.addWithDefaultPublicType(DefaultConvention.java:220)
        at org.gradle.internal.extensibility.DefaultConvention.create(DefaultConvention.java:125)
        at com.vaadin.gradle.VaadinPlugin$_apply_closure1$_closure4.doCall(VaadinPlugin.groovy:112)
        at com.vaadin.gradle.VaadinPlugin$_apply_closure1.doCall(VaadinPlugin.groovy:106)
        at com.vaadin.gradle.VaadinPlugin.apply(VaadinPlugin.groovy:98)
```
