### ISSUE TITLE
vaadinPrepareFrontend task throws FileNotFound exceptions

### ISSUE THREAD

**Issue by cheppsn** [vaadin/vaadin-gradle-plugin#38]
**Desktop:**
 - OS: Windows 10 / Docker (Ubuntu, Gradle 5.0 image)
 - JDK version: 11
 - Gradle version: 5.0
 - Vaadin Plugin version: 0.5.0

**Describe the bug**
We use Vaadin in the "ui" module ("vaadin-lib" in output below) of a multi-module project with Spring-Boot. Our Vaadin-module depends on some other modules. When I execute `clean vaadinPrepareFrontend` the build completes OK, but throws errors (see output below).

The reason is, I believe, that the `prepareFrontend` task tries to expand the built artifacts of the modules it depends on (i.e. the jars) but those don't exist because `prepareFrontend` has been called right after `clean`. I think those should be _silently_ suppressed or just output as debug output.

The same happens, of course, when `buildFrontend` is invoked. Building the other application code first is not really an option, I think, because after building the frontend it should of course be packed into the jar, so it needs to happen before the `jar` task.

Currently this behavior creates ~900 lines of stacktrace output in our build, which is a bit irritating and leads to false alarms.

**To Reproduce**
1. Setup a minimal multi-module gradle project, e.g. "master" with subprojects "vaadin", "common", where "vaadin" has a compile dependency on "common"
2. Run Gradle task 'clean vaadinPrepareFrontend' as documented in README
3. Taks completes successfully but throws errors on console, see output below

**Expected behavior**
No errors on console, complete successfully, so that e.g. `clean vaadinPrepareFrontend build` can be executed without error output.

**Gradle output (edited for content)**

The error output below doubles if `vaadinBuildFrontend` is executed, it occurs once for _prepareFrontend_ and once for _buildFrontend_ task.

```
$ ./gradlew clean vaadinPrepareFrontend build -x test

Starting Gradle Daemon...Connected to the target VM, address: '127.0.0.1:58532', transport: 'socket'
Gradle Daemon started in 5 s 776 ms
> Task :server-app:clean
> Task :server-lib:clean
> Task :shared-lib:clean
> Task :vaadin-lib:clean

> Task :shared-lib:compileJava
> Task :shared-lib:compileJava
... (omitted)
> Task :vaadin-lib:compileJava
> Task :vaadin-lib:vaadinPrepareFrontend
could not create Dir using jarFile from url file:/P:/projects/.../shared-lib/build/libs/shared-lib.jar. skipping.
java.lang.NullPointerException
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:233)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:283)
	at org.reflections.vfs.Vfs$DefaultUrlTypes$1.createDir(Vfs.java:216)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:99)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
	at org.reflections.Reflections.scan(Reflections.java:240)
	at org.reflections.Reflections.scan(Reflections.java:202)
	at org.reflections.Reflections.<init>(Reflections.java:123)
	at com.vaadin.flow.server.scanner.ReflectionsClassFinder.<init>(ReflectionsClassFinder.java:52)
	at com.vaadin.gradle.VaadinUtilsKt.getClassFinder(VaadinUtils.kt:52)
	at com.vaadin.gradle.VaadinPrepareFrontendTask.vaadinPrepareFrontend(VaadinPrepareFrontendTask.kt:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:704)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:671)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:117)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:106)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:85)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:65)
	at org.gradle.api.internal.tasks.execution.ActionEventFiringTaskExecuter.execute(ActionEventFiringTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.TimeoutTaskExecuter.execute(TimeoutTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.SnapshotAfterExecutionTaskExecuter.execute(SnapshotAfterExecutionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:49)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:61)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:49)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:44)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:337)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:325)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:304)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:834)
could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: Could not open url connection
	at org.reflections.vfs.JarInputDir$1$1.<init>(JarInputDir.java:37)
	at org.reflections.vfs.JarInputDir$1.iterator(JarInputDir.java:33)
	at org.reflections.Reflections.scan(Reflections.java:243)
	at org.reflections.Reflections.scan(Reflections.java:202)
	at org.reflections.Reflections.<init>(Reflections.java:123)
	at com.vaadin.flow.server.scanner.ReflectionsClassFinder.<init>(ReflectionsClassFinder.java:52)
	at com.vaadin.gradle.VaadinUtilsKt.getClassFinder(VaadinUtils.kt:52)
	at com.vaadin.gradle.VaadinPrepareFrontendTask.vaadinPrepareFrontend(VaadinPrepareFrontendTask.kt:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:704)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:671)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:117)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:106)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:85)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:65)
	at org.gradle.api.internal.tasks.execution.ActionEventFiringTaskExecuter.execute(ActionEventFiringTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.TimeoutTaskExecuter.execute(TimeoutTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.SnapshotAfterExecutionTaskExecuter.execute(SnapshotAfterExecutionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:49)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:61)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:49)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:44)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:337)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:325)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:304)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.FileNotFoundException: P:\projects\...\shared-lib\build\libs\shared-lib.jar (Das System kann den angegebenen Pfad nicht finden)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
	at org.reflections.vfs.JarInputDir$1$1.<init>(JarInputDir.java:36)
	... 63 more
could not create Dir using jarFile from url file:/P:/projects/.../server-lib/build/libs/server-lib.jar. skipping.
... (stacktraces omitted)
could not create Dir using jarFile from url file:/P:/projects/.../other-lib/build/libs/client-lib.jar. skipping.
... (stacktraces omitted) 
> Task :client-app:compileJava
> Task :client-app:processResources
> Task :client-app:classes
> Task :client-app:jar
... (build continues and completes successfully)
```

**Comment by cheppsn** [comment]
BTW, thanks a lot for releasing this plugin, it's greatly appreciated! 👍

**Comment by cheppsn** [comment]
Of course a workaround is to invoke the build command with `./gradlew clean :shared-lib:jar :server-lib:jar :other-lib:jar vaadinPrepareFrontend build` 

But IMHO it would be be nicer if that were enforced by the `buildFrontend` task (or if the _FileNotFound_ exceptions were silently ignored) because otherwise build scripts have to be adjusted whenever a new dependency is added to the Vaadin module.

**Comment by mstahv** [comment]
@mvysny Did you have a moment to look into this?

**Comment by mvysny** [comment]
Hi, thank you, reproduced. I agree that the problem resides in the fact that all build folders have been deleted by `clean` and not yet populated by the jar artifacts. However, silently suppressing those exceptions may lead to incomplete classpath scanning - e.g. if you have `@JsModule`-annotated components in those jars, they will not be picked by the Vaadin autodetection mechanism and the webpack bundle will be incomplete.

I wonder whether it is possible to tell Gradle to build all dependencies before the vaadinPrepareFrontend is run...

I have found a bit simpler workaround: run gradle in two passes: `./gradlew clean build && ./gradlew server-lib:vaadinPrepareFrontend`; to build the production artifact you can run `./gradlew clean build && ./gradlew server-lib:vaadinBuildFrontend server-lib:build`.

**Comment by cheppsn** [comment]
I agree that suppressing the errors is not a very good solution.

But invoking `./gradlew clean build && ./gradlew server-lib:vaadinPrepareFrontend` will work for dev mode, but not for prod / CI build, because that will build the frontend _after_ packaging the rest (and running the tests).

Gradle has a task `buildDependents` which does exactly what it says, so the `vaadinPrepareFrontend` task could in principle depend on that (for the project/module where it is defined). But that will also force all checks (i.e. tests) to be executed in the dependents, which may not be desired.

Ideally the `vaadinPrepareFrontend` task would analyze the dependents of the module where it is defined and then add `dependsOn` for all those modules' `jar` tasks during the configuration phase (i.e. do automatically what we currently do expicitly as a work-around). That should build the dependents in minimal required state, packaging everything as required for the classpath-scanning that you mention.

That way, the recommended call could still stay `./gradlew clean vaadinPrepareFrontend build` for CI or `./gradlew clean vaadinPrepareFrontend assemble` for dev build (not executing tests).

**Comment by mvysny** [comment]
Thank you. Actually in order to build jars of all dependencies the `buildNeeded` task should be invoked instead. However, `buildNeeded` depends on `build` of this project, which would build the WAR before `vaadinPrepareFrontend` or `vaadinBuildFrontend` would have a chance to generate webpack stuff.

Therefore, I agree with the solution you propose - to analyze the dependent projects and depend on their `assemble` tasks. Let me try to implement such a solution.

**Comment by mvysny** [comment]
I've fixed the issue and added a test for that: https://github.com/vaadin/vaadin-gradle-plugin/pull/45

**Comment by mvysny** [comment]
Fixed by f2b613a90b9ff0dca1195348bb0e0e728203a607

**Comment by cheppsn** [comment]
Hi, we just finally upgraded to Vaadin 0.14.3.7 and tried to remove our work around, but the problems reappeared:

- multimodule gradle project
- Vaadin is just a submodule that depends on more modules
- when executing `gradle assemble` we get the following error and build stops:

```
Execution failed for task ':frontend-ui:vaadinPrepareFrontend'.
<myproject>\backend\api\build\libs\backend-api.jar doesn't exist
```

This used to be just an error in the console, but build would continue.

The following work around fixes this:

```
// prevent FileNotFound exceptions; workaround for https://github.com/vaadin/vaadin-gradle-plugin/issues/38
vaadinPrepareFrontend.dependsOn(':backend-plugin:jar', ':backend-core:jar', ':backend-api:jar', ... <more modules>)
```

**Comment by mvysny** [comment]
Hi, that's exactly what https://github.com/vaadin/vaadin-gradle-plugin/blob/master/src/main/kotlin/com/vaadin/gradle/VaadinPrepareFrontendTask.kt#L52 was designed to do. It basically tries to find all `ProjectDependency`ies on runtime classpath, then depend on their `assemble` tasks which should then depend on their `jar` tasks. However, if this mechanism doesn't work, could you please file a new bug and attach an example project which reproduces the issue?

**Comment by mvysny** [comment]
Even simpler solution: `dependsOn(project.configurations.getByName("runtimeClasspath").filter { it.name.endsWith(".jar", true) })`; no need to figure out projects from dependencies and `assemble` tasks out of projects.

Also see:
* https://github.com/vaadin/flow/issues/11943
* https://github.com/vaadin/vaadin-gradle-plugin/commit/62211dfe80ea824a782d46ef3da1c1c7aabf37f5
