### ISSUE TITLE
Hot-redeployment of code with Gretty 3.0.3 fails

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-gradle-plugin#63]
**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 x86-64
 - JDK version: 8
 - Gradle version: 6.4
 - Vaadin Plugin version: 0.6.0

**Describe the bug**
The hot-redeployment of code with Gretty 3.0.3 fails with dev-webpack suddenly failing to open files which apparently exist on the file-system:
```
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/comboBoxConnector-es6.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/comboBoxConnector-es6.js'
```

**To Reproduce**
1. git clone https://github.com/vaadin/base-starter-gradle
2. run `./gradlew appRun`
3. modify `src/main/java/com/vaadin/starter/skeleton/MainView.java`
4. Wait 5-10 seconds for Gretty to pick up the changes and restart the server
5. Observe webpack-related errors in the terminal.

**Expected behavior**
The new code should redeploy and launch successfully. Instead the webpack compilation fails and browsing localhost:8080 shows only a plain text, with no custom elements loaded.

Full log follows.

**Comment by mvysny** [comment]
The full log:
```
./gradlew appRun
11:04:18 WARN  Ignoring deprecated socket close linger time
[main] INFO com.vaadin.flow.server.startup.DevModeInitializer - Starting dev-mode updaters in /home/mavi/work/vaadin/base-starter-gradle folder.
[main] INFO dev-updater - Visited 83 classes. Took 80 ms.
[main] INFO dev-updater - Added 1 dependencies to main package.json
[main] INFO dev-updater - Updated npm /home/mavi/work/vaadin/base-starter-gradle/package.json.
[main] INFO dev-updater - Updated npm /home/mavi/work/vaadin/base-starter-gradle/package.json.
[main] INFO dev-updater - Running `npm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
npm WARN no-name@ No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

[main] INFO dev-updater - Frontend dependencies resolved successfully.
[main] INFO dev-updater - Copying frontend resources from jar files ...
[main] INFO dev-updater - Visited 11 resources. Took 11 ms.
[main] INFO dev-updater - No js modules to update '/home/mavi/work/vaadin/base-starter-gradle/target/frontend/generated-flow-imports.js' file
[main] INFO dev-webpack - Starting webpack-dev-server, port: 39291 dir: /home/mavi/work/vaadin/base-starter-gradle
[main] INFO dev-webpack - Running webpack to compile frontend resources. This may take a moment, please stand by...
[main] INFO dev-webpack - Webpack startup and compilation completed in 5650ms
[main] INFO com.vaadin.flow.server.startup.ServletDeployer - Automatically deploying Vaadin servlet with name com.vaadin.flow.server.startup.ServletDeployer to /*
11:04:33 INFO  Jetty 9.4.24.v20191120 started and listening on port 8080
11:04:33 INFO   runs at:
11:04:33 INFO    http://localhost:8080/

> Task :appRun
Press any key to stop the server.

[qtp1976752685-13] WARN com.vaadin.flow.server.DefaultDeploymentConfiguration - 
====================================================================
Vaadin is running in DEBUG MODE.
In order to run your application in production mode and disable debug features, you should enable it by setting the servlet init parameter productionMode to true.
See https://vaadin.com/docs/v14/flow/production/tutorial-production-mode-basic.html for more information about the production mode.
====================================================================
11:05:06 WARN  Ignoring deprecated socket close linger time
[main] INFO com.vaadin.flow.server.startup.DevModeInitializer - Starting dev-mode updaters in /home/mavi/work/vaadin/base-starter-gradle folder.
[main] INFO dev-updater - Visited 83 classes. Took 41 ms.
[main] INFO dev-updater - Added 1 dependencies to main package.json
[main] INFO dev-updater - Updated npm /home/mavi/work/vaadin/base-starter-gradle/package.json.
[main] INFO dev-updater - Updated npm /home/mavi/work/vaadin/base-starter-gradle/package.json.
[main] INFO dev-updater - Running `npm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
npm WARN no-name@ No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/comboBoxConnector-es6.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/comboBoxConnector-es6.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 17:0-56
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/comboBoxConnector-es6.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/comboBoxConnector-es6.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 17:0-56
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/comboBoxConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/comboBoxConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 79:0-52
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/comboBoxConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/comboBoxConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 79:0-52
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/contextMenuConnector-es6.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/contextMenuConnector-es6.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 18:0-59
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/contextMenuConnector-es6.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/contextMenuConnector-es6.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 18:0-59
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/contextMenuConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/contextMenuConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 80:0-55
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/contextMenuConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/contextMenuConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 80:0-55
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/datepickerConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/datepickerConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 19:0-54
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/datepickerConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/datepickerConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 19:0-54
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/dndConnector-es6.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/dndConnector-es6.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 20:0-51
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/dndConnector-es6.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/dndConnector-es6.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 20:0-51
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/dndConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/dndConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 81:0-47
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/dndConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/dndConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 81:0-47
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/flow-component-renderer.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/flow-component-renderer.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 21:0-58
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/flow-component-renderer.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/flow-component-renderer.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 21:0-58
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/gridConnector-es6.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/gridConnector-es6.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 22:0-52
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/gridConnector-es6.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/gridConnector-es6.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 22:0-52
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/gridConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/gridConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 82:0-48
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/gridConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/gridConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 82:0-48
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/ironListConnector-es6.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/ironListConnector-es6.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 23:0-56
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/ironListConnector-es6.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/ironListConnector-es6.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 23:0-56
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/ironListConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/ironListConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 83:0-52
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/ironListConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/ironListConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 83:0-52
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/ironListStyles.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/ironListStyles.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 24:0-49
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/ironListStyles.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/ironListStyles.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 24:0-49
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/menubarConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/menubarConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 25:0-51
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/menubarConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/menubarConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 25:0-51
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/selectConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/selectConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 84:0-50
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/selectConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/selectConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 84:0-50
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/timepickerConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/timepickerConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 26:0-54
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/timepickerConnector.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/timepickerConnector.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 26:0-54
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/vaadin-big-decimal-field.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/vaadin-big-decimal-field.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 27:0-59
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/vaadin-big-decimal-field.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/vaadin-big-decimal-field.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 27:0-59
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/vaadin-grid-flow-selection-column.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/vaadin-grid-flow-selection-column.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 28:0-68
[webpack] ERROR dev-webpack - ERROR in ../node_modules/@vaadin/flow-frontend/vaadin-grid-flow-selection-column.js
[webpack] ERROR dev-webpack - Module build failed (from ../node_modules/babel-loader/lib/index.js):
[webpack] ERROR dev-webpack - Error: ENOENT: no such file or directory, open '/home/mavi/work/vaadin/base-starter-gradle/node_modules/@vaadin/flow-frontend/vaadin-grid-flow-selection-column.js'
[webpack] ERROR dev-webpack -  @ ../target/frontend/generated-flow-imports.js 28:0-68
[webpack] ERROR dev-webpack - ℹ ｢wdm｣: Failed to compile.
[webpack] ERROR dev-webpack - 
------------------ Frontend compilation failed. -----------------
[main] INFO dev-updater - Frontend dependencies resolved successfully.
[main] INFO dev-updater - Copying frontend resources from jar files ...
[main] INFO dev-updater - Visited 11 resources. Took 8 ms.
[main] INFO dev-updater - No js modules to update '/home/mavi/work/vaadin/base-starter-gradle/target/frontend/generated-flow-imports.js' file
[main] INFO dev-webpack - Reusing webpack-dev-server running at http://localhost:39291
[main] INFO com.vaadin.flow.server.startup.ServletDeployer - Automatically deploying Vaadin servlet with name com.vaadin.flow.server.startup.ServletDeployer to /*
11:05:13 INFO  Jetty 9.4.24.v20191120 started and listening on port 8080
11:05:13 INFO   runs at:
11:05:13 INFO    http://localhost:8080/
Exception in thread "main" java.lang.NullPointerException
        at org.akhikhl.gretty.Runner$ServerStartEventImpl.onServerStart(Runner.groovy:41)
        at org.akhikhl.gretty.ServerStartEvent$onServerStart.call(Unknown Source)
        at org.akhikhl.gretty.JettyServerManager.startServer(JettyServerManager.groovy:72)
        at org.akhikhl.gretty.ServerManager$startServer$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at org.akhikhl.gretty.Runner.run(Runner.groovy:147)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:70)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
        at org.akhikhl.gretty.Runner.main(Runner.groovy:54)
[qtp1788698111-46] WARN com.vaadin.flow.server.DefaultDeploymentConfiguration - 
====================================================================
Vaadin is running in DEBUG MODE.
In order to run your application in production mode and disable debug features, you should enable it by setting the servlet init parameter productionMode to true.
See https://vaadin.com/docs/v14/flow/production/tutorial-production-mode-basic.html for more information about the production mode.
====================================================================
<===========--> 88% EXECUTING [1m 7s]
> :appRun
^C
```

**Comment by mvysny** [comment]
Workaround is to configure Gretty to reload on class level instead of restarting the entire webapp:
```
gretty {
    managedClassReload = true
}
```

Even though the workaround sometimes produce a nasty `VerificationError`, generally it works really well. The webapp is still redeployed when the dependency set changes, but at least this gives you the opportunity to hot-reload code and minor tweaks.
